DATA_ELEMENTS = [
    "Jzp3DtAI4kM",
    "SsyS3oA46ap",
    "Z6mbKfFjLSr",
    "NydRn0SV4dR",
    "CIB3ptZxOCN",
    "OyKjiiEWoa9",
    "CfkFrDUbn2V",
    "jpz9yBjXuEj",
    "xWv7xixfUAy",
    "cWvBOYmVCmq",
    "vPrd4H6FUyw",
    "wMVloJpLTl6",
    "eRBJOEKmv1d",
    "T75i1ix5PJm",
    "gaT2rrZbeSi",
    "wuqGplL18UN",
    "JxBmpzPCsNU",
    "ySICDa0DYdR",
    "J6362zM0N8N",
    "Pi7rVfzadYK",
    "mNhqTfBm0kc",
    "xyNw0Rz34hz",
    "hinwahZrR03",
    "jlEW1Fe1dZV",
    "Y7ngiZ8a8t7",
    "allACdvy3rB",
    "fP3165s5f2p",
    "yB6Km3zjFEk",
    "j6LBb5lzfzH",
    "rSGzGLp4n2a",
    "HyP4KapEOfB",
    "AVcQb0a4VVl",
    "r7ugSfIvuYw",
    "eWOytfDFlG2",
    "ZXdCyi2f1Jg",
    "VupaFwzwDJV",
    "Lzkl7cTY3S8",
    "hPD1clmIPcH",
    "ZJ0sFYbJW4P",
    "lNr8Ja9HL3Z",
    "DanQYFufCL0",
    "Fo81GUHqFhb",
    "OZyvZGn4wxR",
    "cob2xrwlIGx",
    "DQHIDBGkZ4g",
    "By3Ek3tiUsL",
    "hcVu1gFkt0W",
    "TPe9uUCdila",
    "lsFVTErT767",
    "xvWqDN3MZYs",
    "NSIE9Q7TNnl",
    "cavbsoNnr2w",
    "atxdvBU3SLR",
    "OLYw0VtSeuR",
    "FfNkGNRwHDm",
    "FkSa4RCLWRz",
    "sUCZfSdPhNf",
    "Jxc4JmnVNqN",
    "BGPENcxS2pf",
    "BhHVgWkOk40",
    "MjiyaMNmuyh",
    "Kd8YowZicyM",
    "s35SRE86kQh",
    "YsxNGGd1tsp",
    "ej1VOHbHnCs",
    "qr4xTm2kLVC",
    "C4VBtvHuNTM",
    "XcFTKVJTdcC",
    "CSOqQr26BLh",
    "MY617rWRI4D",
    "EQAbEGqtQM3",
    "FpDDxih7qpZ",
    "eNOMUNDOuxV",
    "u3MjZeooCwx",
    "m6kCMzBrXvq",
    "ZAzBlK18saJ",
    "pjf9x3pUkpc",
    "Ix7y3zKBGM0",
    "d8q1XQd9V2v",
    "E8DuSvBVnV9",
    "yh2jSdm1suw",
    "rjS1iNRK8fP",
    "biySuhRn79K",
    "HiCYvltnIp5",
    "Xqk3ZqWlMj3",
    "hy4Qvv08Fbe",
    "B8P4IP1QAzp",
    "pwJ9T1fRpE4",
    "meWgY6eg5Tz",
    "DKqHVeSMOAA",
    "KXHzhjIoghS",
    "hkIA9Y8eBKu",
    "ncJrbfjtHCf",
    "Hfzn1MAtVFq",
    "KE2rVt05Hwd",
    "XhDjQmvyMjO",
    "W4GaZb4dzCO",
    "jjyHWcmKDuD",
    "Joi1yVeRb7y",
    "GwvxVFMuAWo",
    "pNCQFe2Z0eS",
    "wqRxOMW0evN",
    "DKjuABPn9V2",
    "VT1gvZdINJh",
    "fmxxir0RPc7",
    "F0fMiidIA32",
    "kZEr9mhdEXY",
    "TxmlApxgBlU",
    "q6IrYbibICS",
    "m6suo4OxCg0",
    "VezaBPmkIKt",
    "B1iQS0QybpG",
    "GkdphJ2w9Tw",
    "q2W8qkwTzp5",
    "TNVvaDs9wfc",
    "IfsrSma9G0x",
    "QWTGteclWSn",
    "iHtzLWXSZ9w",
    "rXknXLRqJy1",
    "BFXf3mTwQI7",
    "wjLLHdRBZJO",
    "PzB91cDzy9q",
    "XjTQSdzdAwl",
    "quohgzjLio3",
    "aO35dISHYCf",
    "z4gUlqsI2G7",
    "JhgHzHyOBGJ",
    "s7agDWyjMWW",
    "VZhymPvwC6j",
    "ktqFMrrs1Om",
    "gnbKuarj0qj",
    "YaVGGUj2BN0",
    "DAlDhRfgPpa",
    "ftAkseWxBFP",
    "nUCqISZiVDM",
    "FFPL8EBoeMd",
    "BNPvOYpdjvU",
    "YDot5SUphZV",
    "jr6m2WAXchp",
]


DATASET_IDS = [
    "FPnSqZEJiGv",  # "I.1. Activités de consultations et de soins A"
    "hPJLYYJbFWA",  # "I.1. Activités de consultations et de soins B et C"
    "AkWapnu8H49",  # "I.2. Activités de Suivi de la mère et de l'enfant"
    "HYSnqJHYmqp",  # "II.1. Morbidité"
    "yWhYELONjoJ",  # "II.2. Morbidité diagnostiquée en consultations B et C"
    "ZKEMMdlSbqU",  # "III.1. Mortalité"
    "yqhkV13v7IK",  # "III.2. MORTALITE B et C"
    "LRcA6gVCiKU",  # "IV. Réalisation des Tests Rapides de Dépistage au niveau poste"
    "mcPlUnUcbXN",  # V. Equipements Techniques
    "m4UgyqVtRAU",  # VII. Equipements techniques B et C
    "x6z1nTTPhox",  # Rapport Mensuel des Activités Communautaires du Centre de Santé
]
